-- =============================================================================
-- Rista Sales — RAW tables (v2: one row per invoice)
--
-- Prerequisite: sql/001_setup_env.sql (warehouse, database, schema, role, grants)
--
-- Current-state tables: PRIMARY KEY on INVOICE_NUMBER (globally unique).
-- Re-extract merge rules: docs/section-05-sales-load-merge.md
-- =============================================================================

-- -----------------------------------------------------------------------------
-- SALES_HEADER — one current row per INVOICE_NUMBER
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_HEADER (
  INVOICE_NUMBER                VARCHAR NOT NULL,

  BRANCH_CODE                   VARCHAR NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,
  REQUESTED_DAY                 DATE NOT NULL,
  REQUESTED_STATUS              VARCHAR,

  BRANCH_NAME                   VARCHAR,
  BRAND_NAME                    VARCHAR,
  BRANCH_STATE                  VARCHAR,
  BRANCH_TIN                    VARCHAR,
  STATEMENT_NUMBER              VARCHAR,
  INVOICE_DATE                  TIMESTAMP_NTZ,
  INVOICE_DAY                   DATE,
  CREATED_DATE                  TIMESTAMP_NTZ,
  MODIFIED_DATE                 TIMESTAMP_NTZ,
  DEVICE_LABEL                  VARCHAR,
  CHARGE_TAX_TOTAL              NUMBER(18, 2),
  INVOICE_TYPE                  VARCHAR,
  NOTE                          VARCHAR,
  FULFILLMENT_STATUS            VARCHAR,
  LABEL                         VARCHAR,
  CHANNEL                       VARCHAR,
  CURRENCY                      VARCHAR,
  ITEM_COUNT                    NUMBER(10, 0),
  PERSON_COUNT                  NUMBER(10, 0),
  KDS_ORDER_IN_PROCESS          TIMESTAMP_NTZ,
  ORDER_READY_TIMESTAMP         TIMESTAMP_NTZ,
  ITEM_TOTAL_AMOUNT             NUMBER(18, 2),
  DISCOUNT_AMOUNT               NUMBER(18, 2),
  ITEM_DISCOUNT_AMOUNT          NUMBER(18, 2),
  TOTAL_DISCOUNT_AMOUNT         NUMBER(18, 2),
  DIRECT_CHARGE_AMOUNT          NUMBER(18, 2),
  CHARGE_AMOUNT                 NUMBER(18, 2),
  TAX_AMOUNT_INCLUDED           NUMBER(18, 2),
  TAX_AMOUNT_EXCLUDED           NUMBER(18, 2),
  TAX_AMOUNT                    NUMBER(18, 2),
  BILL_AMOUNT                   NUMBER(18, 2),
  GROSS_AMOUNT                  NUMBER(18, 2),
  NET_DISCOUNT_AMOUNT           NUMBER(18, 2),
  NET_AMOUNT                    NUMBER(18, 2),
  NET_DIRECT_CHARGE_AMOUNT      NUMBER(18, 2),
  NET_CHARGE_AMOUNT             NUMBER(18, 2),
  ROUND_OFF_AMOUNT              NUMBER(18, 2),
  BILL_ROUNDED_AMOUNT           NUMBER(18, 2),
  TIP_AMOUNT                    NUMBER(18, 2),
  TOTAL_COST                    NUMBER(18, 2),
  TOTAL_MATERIAL_COST           NUMBER(18, 2),
  TOTAL_SUPPLIES_COST           NUMBER(18, 2),
  BALANCE_AMOUNT                NUMBER(18, 2),
  TOTAL_AMOUNT                  NUMBER(18, 2),
  TAX_ROUND_OFF                 NUMBER(18, 2),
  ACCOUNTING_ROUND_OFF          NUMBER(18, 2),
  REPRINT_COUNT                 NUMBER(10, 0),
  URL                           VARCHAR,
  STATUS                        VARCHAR,
  SALE_BY                       VARCHAR,
  SALE_BY_USER_ID               VARCHAR,

  DELIVERY_BY_NAME              VARCHAR,
  DELIVERY_BY_PHONE             VARCHAR,

  RESOURCE_NAME                 VARCHAR,
  RESOURCE_GROUP_SIZE           NUMBER(10, 0),

  STATUS_INFO_REASON            VARCHAR,
  STATUS_INFO_REMARKS           VARCHAR,

  TAGS                          VARIANT,
  TAG_COUNT                     NUMBER(10, 0),

  TAXES_DETAIL                  VARIANT,
  TAXES_TOTAL_AMOUNT            NUMBER(18, 2),

  OVERALL_REFUNDS_DETAIL        VARIANT,
  OVERALL_REFUNDS_TOTAL_AMOUNT  NUMBER(18, 2),

  REPRINT_EVENTS_DETAIL         VARIANT,
  REPRINT_EVENTS_COUNT          NUMBER(10, 0),

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER)
)
CLUSTER BY (INVOICE_DAY, BRANCH_CODE);


-- -----------------------------------------------------------------------------
-- SALES_INVOICE_HISTORY — CREATED BUT NEVER WRITTEN
--
-- Intended to hold archived snapshots when a re-extract changes NET_AMOUNT: two
-- rows per conflict, SUPERSEDED (old current) + INCOMING (new extract).
--
-- The pipeline has no code path that inserts into this table. The per-invoice
-- merge described in docs/section-05 was designed and never implemented; the
-- transformer deletes and re-inserts a whole business day instead. The table is
-- retained so the feature can be added without a schema migration.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_INVOICE_HISTORY (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  HISTORY_ENTRY_SEQ             NUMBER(10, 0) NOT NULL,

  CONFLICT_GROUP_ID             VARCHAR NOT NULL,
  SNAPSHOT_ROLE                 VARCHAR NOT NULL,

  EXTRACTED_DAY                 DATE NOT NULL,
  REEXTRACTION_REQUESTED_DAY    DATE NOT NULL,

  NET_AMOUNT                    NUMBER(18, 2),
  BRANCH_CODE                   VARCHAR,
  INVOICE_DAY                   DATE,
  HEADER_SNAPSHOT               VARIANT,

  RECORDED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER, HISTORY_ENTRY_SEQ)
)
CLUSTER BY (INVOICE_NUMBER, REEXTRACTION_REQUESTED_DAY);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_DELIVERY (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  DELIVERY_NAME                 VARCHAR,
  DELIVERY_MODE                 VARCHAR,
  DELIVERY_DATE                 TIMESTAMP_NTZ,
  DELIVERY_EMAIL                VARCHAR,
  DELIVERY_PHONE_NUMBER         VARCHAR,
  DELIVERY_TITLE                VARCHAR,
  DELIVERY_PAYMENT_MODE         VARCHAR,

  ADDRESS_LINE                  VARCHAR,
  ADDRESS_CITY                  VARCHAR,
  ADDRESS_STATE                 VARCHAR,
  ADDRESS_COUNTRY               VARCHAR,
  ADDRESS_ZIP                   VARCHAR,
  ADDRESS_LANDMARK              VARCHAR,
  ADDRESS_LABEL                 VARCHAR,

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_SOURCE_INFO (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  COMPANY_NAME                  VARCHAR,
  SOURCE_INVOICE_NUMBER         VARCHAR,
  SOURCE_INVOICE_DATE           TIMESTAMP_NTZ,
  SOURCE                        VARCHAR,
  SOURCE_OUTLET_ID              VARCHAR,
  OUTLET_ID                     VARCHAR,
  IS_ECOM_ORDER                 BOOLEAN,

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_SOURCE_CUSTOMER_DETAIL (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  SOURCE_CUSTOMER_ID            VARCHAR,
  SOURCE                        VARCHAR,
  SOURCE_CUSTOMER_NAME          VARCHAR,
  SOURCE_ORDER_INSTRUCTIONS     VARCHAR,
  PIN_CODE                      VARCHAR,
  DELIVERY_COORDINATES_TYPE     VARCHAR,
  CITY                          VARCHAR,
  STATE                         VARCHAR,
  COUNTRY                       VARCHAR,
  ADDRESS_TYPE                  VARCHAR,

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_CUSTOMER (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  CUSTOMER_NAME                 VARCHAR,
  CUSTOMER_TITLE                VARCHAR,
  CUSTOMER_PHONE_NUMBER         VARCHAR,
  CUSTOMER_ID                   VARCHAR,

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_CHARGES (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  CHARGE_SEQ                    NUMBER(5, 0) NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  CHARGE_NAME                   VARCHAR,
  CHARGE_TYPE                   VARCHAR,
  CHARGE_RATE                   NUMBER(18, 2),
  CHARGE_SALE_AMOUNT            NUMBER(18, 2),
  CHARGE_AMOUNT                 NUMBER(18, 2),
  IS_DIRECT_CHARGE              BOOLEAN,
  CHARGE_TAX_AMOUNT_INCLUDED    NUMBER(18, 2),
  CHARGE_TAX_AMOUNT_EXCLUDED    NUMBER(18, 2),
  CHARGE_TAX_AMOUNT             NUMBER(18, 2),

  CHARGE_TAXES_DETAIL           VARIANT,
  CHARGE_TAXES_TOTAL_AMOUNT     NUMBER(18, 2),

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER, CHARGE_SEQ)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_DISCOUNTS (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  DISCOUNT_SEQ                  NUMBER(5, 0) NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  DISCOUNT_NAME                 VARCHAR,
  DISCOUNT_TYPE                 VARCHAR,
  DISCOUNT_RATE                 NUMBER(18, 2),
  DISCOUNT_SALE_AMOUNT          NUMBER(18, 2),
  DISCOUNT_AMOUNT               NUMBER(18, 2),
  LOYALTY_POINTS                NUMBER(18, 2),
  APPLIED_BY                    VARCHAR,

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER, DISCOUNT_SEQ)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_PAYMENTS (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  PAYMENT_SEQ                   NUMBER(5, 0) NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  PAYMENT_MODE                  VARCHAR,
  PAYMENT_AMOUNT                NUMBER(18, 2),
  PAYMENT_REFERENCE             VARCHAR,

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER, PAYMENT_SEQ)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_EVENT_LOG (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  EVENT_SEQ                     NUMBER(5, 0) NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  EVENT_STATUS                  VARCHAR,
  EVENT_BY_USER_NAME            VARCHAR,
  EVENT_DATE                    TIMESTAMP_NTZ,
  EVENT_NOTE                    VARCHAR,

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER, EVENT_SEQ)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_ITEMS (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  ITEM_NUMBER                   NUMBER(10, 0) NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  SHORT_NAME                    VARCHAR,
  LONG_NAME                     VARCHAR,
  VARIANTS                      VARCHAR,
  SKU_CODE                      VARCHAR,
  CATEGORY_NAME                 VARCHAR,
  SUB_CATEGORY_NAME             VARCHAR,
  BRAND_NAME                    VARCHAR,
  QUANTITY                      NUMBER(18, 4),
  UNIT_PRICE                    NUMBER(18, 2),
  MEASURING_UNIT                VARCHAR,
  ITEM_NATURE                   VARCHAR,
  ITEM_AMOUNT                   NUMBER(18, 2),
  OPTION_AMOUNT                 NUMBER(18, 2),
  TAX_CODE                      VARCHAR,
  DISCOUNT_AMOUNT               NUMBER(18, 2),
  FACTORED_DISCOUNT_AMOUNT      NUMBER(18, 2),
  ITEM_TOTAL_AMOUNT             NUMBER(18, 2),
  GROSS_AMOUNT                  NUMBER(18, 2),
  NET_DISCOUNT_AMOUNT           NUMBER(18, 2),
  NET_AMOUNT                    NUMBER(18, 2),
  TAX_AMOUNT_INCLUDED           NUMBER(18, 2),
  TAX_AMOUNT_EXCLUDED           NUMBER(18, 2),
  TAX_AMOUNT                    NUMBER(18, 2),
  ITEM_COST                     NUMBER(18, 2),
  ITEM_MATERIAL_COST            NUMBER(18, 2),
  ITEM_SUPPLIES_COST            NUMBER(18, 2),
  NOTE                          VARCHAR,
  CREATED_TIME                  TIMESTAMP_NTZ,
  CREATED_BY                    VARCHAR,
  KOT_NUMBER                    VARCHAR,
  AGGREGATOR_IMAGE_URL          VARCHAR,
  BASE_GROSS_AMOUNT             NUMBER(18, 2),
  BASE_NET_DISCOUNT_AMOUNT      NUMBER(18, 2),
  BASE_NET_AMOUNT               NUMBER(18, 2),
  BASE_TAX_AMOUNT               NUMBER(18, 2),
  KOT_STATUS                    VARCHAR,
  KOT_TIMESTAMP                 TIMESTAMP_NTZ,
  KDS_READY                     TIMESTAMP_NTZ,

  LINE_TAXES_DETAIL             VARIANT,
  LINE_TAXES_TOTAL_AMOUNT       NUMBER(18, 2),

  ITEM_LOG_DETAIL               VARIANT,
  BATCHES_DETAIL                VARIANT,

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER, ITEM_NUMBER)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_ITEM_OPTIONS (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  ITEM_NUMBER                   NUMBER(10, 0) NOT NULL,
  OPTION_SEQ                    NUMBER(5, 0) NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  OPTION_TYPE                   VARCHAR,
  OPTION_ID                     VARCHAR,
  OPTION_NAME                   VARCHAR,
  OPTION_ITEM_NAME              VARCHAR,
  OPTION_VARIANTS               VARCHAR,
  OPTION_SKU_CODE               VARCHAR,
  OPTION_CATEGORY_NAME          VARCHAR,
  OPTION_BRAND_NAME             VARCHAR,
  OPTION_QUANTITY               NUMBER(18, 4),
  OPTION_UNIT_PRICE             NUMBER(18, 2),
  OPTION_AMOUNT                 NUMBER(18, 2),
  OPTION_TAX_CODE               VARCHAR,
  OPTION_GROSS_AMOUNT           NUMBER(18, 2),
  OPTION_NET_DISCOUNT_AMOUNT    NUMBER(18, 2),
  OPTION_NET_AMOUNT             NUMBER(18, 2),
  OPTION_TAX_AMOUNT             NUMBER(18, 2),

  OPTION_TAXES_DETAIL           VARIANT,
  OPTION_TAXES_TOTAL_AMOUNT     NUMBER(18, 2),

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER, ITEM_NUMBER, OPTION_SEQ)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_ITEM_EVENT_LOG (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  ITEM_NUMBER                   NUMBER(10, 0) NOT NULL,
  EVENT_SEQ                     NUMBER(5, 0) NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  EVENT_STATUS                  VARCHAR,
  EVENT_BY_USER_NAME            VARCHAR,
  EVENT_DATE                    TIMESTAMP_NTZ,
  EVENT_NOTE                    VARCHAR,

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER, ITEM_NUMBER, EVENT_SEQ)
)
CLUSTER BY (INVOICE_NUMBER);


CREATE TABLE IF NOT EXISTS SALES_DB.RAW.SALES_ITEM_DISCOUNTS (
  INVOICE_NUMBER                VARCHAR NOT NULL,
  ITEM_NUMBER                   NUMBER(10, 0) NOT NULL,
  DISCOUNT_SEQ                  NUMBER(5, 0) NOT NULL,
  LAST_EXTRACTED_DAY            DATE NOT NULL,

  BRANCH_CODE                   VARCHAR,
  DISCOUNT_NAME                 VARCHAR,
  DISCOUNT_TYPE                 VARCHAR,
  DISCOUNT_RATE                 NUMBER(18, 2),
  DISCOUNT_SALE_AMOUNT          NUMBER(18, 2),
  DISCOUNT_AMOUNT               NUMBER(18, 2),
  APPLIED_BY                    VARCHAR,

  LOADED_AT                     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PRIMARY KEY (INVOICE_NUMBER, ITEM_NUMBER, DISCOUNT_SEQ)
)
CLUSTER BY (INVOICE_NUMBER);


GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_HEADER                    TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_INVOICE_HISTORY          TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_DELIVERY                   TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_SOURCE_INFO                TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_SOURCE_CUSTOMER_DETAIL   TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_CUSTOMER                    TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_CHARGES                     TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_DISCOUNTS                   TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_PAYMENTS                    TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_EVENT_LOG                  TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_ITEMS                       TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_ITEM_OPTIONS                TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_ITEM_EVENT_LOG              TO ROLE SALES_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SALES_DB.RAW.SALES_ITEM_DISCOUNTS              TO ROLE SALES_LOADER_ROLE;