-- =============================================================================
-- Rista Sales — post-load validation & referential integrity checks
--
-- Run in Snowflake after transformer load (VARIANT parse optional but recommended).
-- Prerequisite: sql/003_sales_tables.sql
--
-- Usage:
--   1. Set the session variables in §0 to the business day you loaded.
--   2. Run the full script, or run sections individually.
--   3. §9 "VALIDATION_SUMMARY" should return zero rows with STATUS = 'FAIL'.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- §0  Parameters (edit before run)
-- -----------------------------------------------------------------------------
SET VALIDATION_LAST_EXTRACTED_DAY = '2026-06-01';  -- rows touched by extract/load
SET VALIDATION_BRANCH_CODE = NULL;                 -- e.g. 'BR01' or NULL = all branches

-- Optional: also filter header by REQUESTED_DAY (usually same as LAST_EXTRACTED_DAY)
SET VALIDATION_REQUESTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY;


-- =============================================================================
-- §1  Load volume & freshness (per table)
-- =============================================================================
SELECT '§1_LOAD_VOLUME' AS REPORT_SECTION;

SELECT
    'SALES_HEADER' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT BRANCH_CODE) AS BRANCH_COUNT,
    MIN(LOADED_AT) AS MIN_LOADED_AT,
    MAX(LOADED_AT) AS MAX_LOADED_AT,
    MAX(UPDATED_AT) AS MAX_UPDATED_AT
FROM SALES_DB.RAW.SALES_HEADER
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_ITEMS', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_ITEMS
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_DELIVERY', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_DELIVERY
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_CUSTOMER', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_CUSTOMER
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_SOURCE_INFO', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_SOURCE_INFO
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_SOURCE_CUSTOMER_DETAIL', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_SOURCE_CUSTOMER_DETAIL
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_CHARGES', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_CHARGES
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_DISCOUNTS', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_DISCOUNTS
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_PAYMENTS', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_PAYMENTS
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_EVENT_LOG', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_EVENT_LOG
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_ITEM_OPTIONS', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_ITEM_OPTIONS
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_ITEM_EVENT_LOG', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_ITEM_EVENT_LOG
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_ITEM_DISCOUNTS', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(LOADED_AT), MAX(LOADED_AT), MAX(UPDATED_AT)
FROM SALES_DB.RAW.SALES_ITEM_DISCOUNTS
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

UNION ALL
SELECT 'SALES_INVOICE_HISTORY', COUNT(*), COUNT(DISTINCT BRANCH_CODE), MIN(RECORDED_AT), MAX(RECORDED_AT), MAX(RECORDED_AT)
FROM SALES_DB.RAW.SALES_INVOICE_HISTORY
WHERE REEXTRACTION_REQUESTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)

ORDER BY TABLE_NAME;


-- Header vs line grain for the validation day
SELECT '§1_HEADER_VS_LINES' AS REPORT_SECTION;

SELECT
    h.INVOICE_COUNT,
    i.LINE_COUNT,
    i.INVOICES_WITH_LINES,
    ROUND(i.LINE_COUNT / NULLIF(h.INVOICE_COUNT, 0), 2) AS AVG_LINES_PER_INVOICE
FROM (
    SELECT COUNT(*) AS INVOICE_COUNT
    FROM SALES_DB.RAW.SALES_HEADER h
    WHERE h.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND ($VALIDATION_BRANCH_CODE IS NULL OR h.BRANCH_CODE = $VALIDATION_BRANCH_CODE)
) h
CROSS JOIN (
    SELECT
        COUNT(*) AS LINE_COUNT,
        COUNT(DISTINCT INVOICE_NUMBER) AS INVOICES_WITH_LINES
    FROM SALES_DB.RAW.SALES_ITEMS i
    WHERE i.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND ($VALIDATION_BRANCH_CODE IS NULL OR i.BRANCH_CODE = $VALIDATION_BRANCH_CODE)
) i;


-- =============================================================================
-- §2  Primary key uniqueness (should return no rows)
-- =============================================================================
SELECT '§2_PK_DUPLICATES' AS REPORT_SECTION;

SELECT 'SALES_HEADER' AS TABLE_NAME, INVOICE_NUMBER AS KEY_VALUE, COUNT(*) AS DUPLICATE_COUNT
FROM SALES_DB.RAW.SALES_HEADER
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
GROUP BY INVOICE_NUMBER
HAVING COUNT(*) > 1

UNION ALL
SELECT 'SALES_DELIVERY', INVOICE_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_DELIVERY
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
GROUP BY INVOICE_NUMBER
HAVING COUNT(*) > 1

UNION ALL
SELECT 'SALES_CUSTOMER', INVOICE_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_CUSTOMER
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
GROUP BY INVOICE_NUMBER
HAVING COUNT(*) > 1

UNION ALL
SELECT 'SALES_SOURCE_INFO', INVOICE_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_SOURCE_INFO
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
GROUP BY INVOICE_NUMBER
HAVING COUNT(*) > 1

UNION ALL
SELECT 'SALES_SOURCE_CUSTOMER_DETAIL', INVOICE_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_SOURCE_CUSTOMER_DETAIL
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
GROUP BY INVOICE_NUMBER
HAVING COUNT(*) > 1

UNION ALL
SELECT 'SALES_CHARGES', INVOICE_NUMBER || '|' || CHARGE_SEQ::VARCHAR, COUNT(*)
FROM SALES_DB.RAW.SALES_CHARGES
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
GROUP BY INVOICE_NUMBER, CHARGE_SEQ
HAVING COUNT(*) > 1

UNION ALL
SELECT 'SALES_ITEMS', INVOICE_NUMBER || '|' || ITEM_NUMBER::VARCHAR, COUNT(*)
FROM SALES_DB.RAW.SALES_ITEMS
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
GROUP BY INVOICE_NUMBER, ITEM_NUMBER
HAVING COUNT(*) > 1;


-- =============================================================================
-- §3  Referential integrity — child → SALES_HEADER (orphans)
--     Expect zero rows: every child INVOICE_NUMBER exists on header for that extract day
-- =============================================================================
SELECT '§3_ORPHAN_CHILDREN' AS REPORT_SECTION;

WITH header_keys AS (
    SELECT INVOICE_NUMBER
    FROM SALES_DB.RAW.SALES_HEADER
    WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)
)
SELECT 'SALES_ITEMS' AS CHILD_TABLE, c.INVOICE_NUMBER, COUNT(*) AS ORPHAN_ROWS
FROM SALES_DB.RAW.SALES_ITEMS c
LEFT JOIN header_keys h ON c.INVOICE_NUMBER = h.INVOICE_NUMBER
WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR c.BRANCH_CODE = $VALIDATION_BRANCH_CODE)
  AND h.INVOICE_NUMBER IS NULL
GROUP BY c.INVOICE_NUMBER

UNION ALL
SELECT 'SALES_DELIVERY', c.INVOICE_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_DELIVERY c
LEFT JOIN header_keys h ON c.INVOICE_NUMBER = h.INVOICE_NUMBER
WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND h.INVOICE_NUMBER IS NULL
GROUP BY c.INVOICE_NUMBER

UNION ALL
SELECT 'SALES_CUSTOMER', c.INVOICE_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_CUSTOMER c
LEFT JOIN header_keys h ON c.INVOICE_NUMBER = h.INVOICE_NUMBER
WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND h.INVOICE_NUMBER IS NULL
GROUP BY c.INVOICE_NUMBER

UNION ALL
SELECT 'SALES_CHARGES', c.INVOICE_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_CHARGES c
LEFT JOIN header_keys h ON c.INVOICE_NUMBER = h.INVOICE_NUMBER
WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND h.INVOICE_NUMBER IS NULL
GROUP BY c.INVOICE_NUMBER

UNION ALL
SELECT 'SALES_PAYMENTS', c.INVOICE_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_PAYMENTS c
LEFT JOIN header_keys h ON c.INVOICE_NUMBER = h.INVOICE_NUMBER
WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND h.INVOICE_NUMBER IS NULL
GROUP BY c.INVOICE_NUMBER

UNION ALL
SELECT 'SALES_ITEM_OPTIONS', c.INVOICE_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_ITEM_OPTIONS c
LEFT JOIN header_keys h ON c.INVOICE_NUMBER = h.INVOICE_NUMBER
WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND h.INVOICE_NUMBER IS NULL
GROUP BY c.INVOICE_NUMBER

ORDER BY CHILD_TABLE, INVOICE_NUMBER
LIMIT 100;


-- =============================================================================
-- §4  Referential integrity — header → optional 1:1 satellites (coverage)
--     Informational: invoices missing optional child rows (not always an error)
-- =============================================================================
SELECT '§4_OPTIONAL_SATELLITE_COVERAGE' AS REPORT_SECTION;

WITH hdr AS (
    SELECT INVOICE_NUMBER, BRANCH_CODE, NET_AMOUNT, CHANNEL
    FROM SALES_DB.RAW.SALES_HEADER
    WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)
)
SELECT
    COUNT(*) AS HEADER_COUNT,
    COUNT(d.INVOICE_NUMBER) AS WITH_DELIVERY,
    COUNT(cu.INVOICE_NUMBER) AS WITH_CUSTOMER,
    COUNT(si.INVOICE_NUMBER) AS WITH_SOURCE_INFO,
    COUNT(sc.INVOICE_NUMBER) AS WITH_SOURCE_CUSTOMER,
    COUNT(*) - COUNT(d.INVOICE_NUMBER) AS HEADERS_WITHOUT_DELIVERY,
    COUNT(*) - COUNT(cu.INVOICE_NUMBER) AS HEADERS_WITHOUT_CUSTOMER
FROM hdr h
LEFT JOIN SALES_DB.RAW.SALES_DELIVERY d
    ON h.INVOICE_NUMBER = d.INVOICE_NUMBER AND d.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
LEFT JOIN SALES_DB.RAW.SALES_CUSTOMER cu
    ON h.INVOICE_NUMBER = cu.INVOICE_NUMBER AND cu.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
LEFT JOIN SALES_DB.RAW.SALES_SOURCE_INFO si
    ON h.INVOICE_NUMBER = si.INVOICE_NUMBER AND si.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
LEFT JOIN SALES_DB.RAW.SALES_SOURCE_CUSTOMER_DETAIL sc
    ON h.INVOICE_NUMBER = sc.INVOICE_NUMBER AND sc.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY;


-- =============================================================================
-- §5  Line-level FK — item children → SALES_ITEMS
-- =============================================================================
SELECT '§5_ORPHAN_LINE_CHILDREN' AS REPORT_SECTION;

WITH item_keys AS (
    SELECT INVOICE_NUMBER, ITEM_NUMBER
    FROM SALES_DB.RAW.SALES_ITEMS
    WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)
)
SELECT 'SALES_ITEM_OPTIONS' AS CHILD_TABLE, c.INVOICE_NUMBER, c.ITEM_NUMBER, COUNT(*) AS ORPHAN_ROWS
FROM SALES_DB.RAW.SALES_ITEM_OPTIONS c
LEFT JOIN item_keys k
    ON c.INVOICE_NUMBER = k.INVOICE_NUMBER AND c.ITEM_NUMBER = k.ITEM_NUMBER
WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND k.INVOICE_NUMBER IS NULL
GROUP BY c.INVOICE_NUMBER, c.ITEM_NUMBER

UNION ALL
SELECT 'SALES_ITEM_EVENT_LOG', c.INVOICE_NUMBER, c.ITEM_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_ITEM_EVENT_LOG c
LEFT JOIN item_keys k
    ON c.INVOICE_NUMBER = k.INVOICE_NUMBER AND c.ITEM_NUMBER = k.ITEM_NUMBER
WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND k.INVOICE_NUMBER IS NULL
GROUP BY c.INVOICE_NUMBER, c.ITEM_NUMBER

UNION ALL
SELECT 'SALES_ITEM_DISCOUNTS', c.INVOICE_NUMBER, c.ITEM_NUMBER, COUNT(*)
FROM SALES_DB.RAW.SALES_ITEM_DISCOUNTS c
LEFT JOIN item_keys k
    ON c.INVOICE_NUMBER = k.INVOICE_NUMBER AND c.ITEM_NUMBER = k.ITEM_NUMBER
WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND k.INVOICE_NUMBER IS NULL
GROUP BY c.INVOICE_NUMBER, c.ITEM_NUMBER

ORDER BY CHILD_TABLE, INVOICE_NUMBER, ITEM_NUMBER
LIMIT 100;


-- Headers with no line items (may be valid for some invoice types — review sample)
SELECT '§5_HEADERS_WITHOUT_LINES' AS REPORT_SECTION;

SELECT h.INVOICE_NUMBER, h.BRANCH_CODE, h.INVOICE_TYPE, h.STATUS, h.NET_AMOUNT, h.ITEM_COUNT
FROM SALES_DB.RAW.SALES_HEADER h
LEFT JOIN SALES_DB.RAW.SALES_ITEMS i
    ON h.INVOICE_NUMBER = i.INVOICE_NUMBER
   AND i.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
WHERE h.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR h.BRANCH_CODE = $VALIDATION_BRANCH_CODE)
  AND i.INVOICE_NUMBER IS NULL
ORDER BY h.BRANCH_CODE, h.INVOICE_NUMBER
LIMIT 50;


-- =============================================================================
-- §6  Cross-table consistency (branch, extract day, requested day)
-- =============================================================================
SELECT '§6_BRANCH_MISMATCH' AS REPORT_SECTION;

SELECT
    c.TABLE_NAME,
    c.INVOICE_NUMBER,
    c.CHILD_BRANCH,
    h.BRANCH_CODE AS HEADER_BRANCH
FROM (
    SELECT 'SALES_ITEMS' AS TABLE_NAME, INVOICE_NUMBER, BRANCH_CODE AS CHILD_BRANCH
    FROM SALES_DB.RAW.SALES_ITEMS WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
    UNION ALL
    SELECT 'SALES_CHARGES', INVOICE_NUMBER, BRANCH_CODE
    FROM SALES_DB.RAW.SALES_CHARGES WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
    UNION ALL
    SELECT 'SALES_PAYMENTS', INVOICE_NUMBER, BRANCH_CODE
    FROM SALES_DB.RAW.SALES_PAYMENTS WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
) c
JOIN SALES_DB.RAW.SALES_HEADER h ON c.INVOICE_NUMBER = h.INVOICE_NUMBER
WHERE h.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND c.CHILD_BRANCH IS NOT NULL
  AND h.BRANCH_CODE IS NOT NULL
  AND c.CHILD_BRANCH <> h.BRANCH_CODE
LIMIT 100;


SELECT '§6_LAST_EXTRACTED_DAY_MISMATCH' AS REPORT_SECTION;

SELECT
    'SALES_ITEMS' AS CHILD_TABLE,
    i.INVOICE_NUMBER,
    i.LAST_EXTRACTED_DAY AS CHILD_DAY,
    h.LAST_EXTRACTED_DAY AS HEADER_DAY
FROM SALES_DB.RAW.SALES_ITEMS i
JOIN SALES_DB.RAW.SALES_HEADER h ON i.INVOICE_NUMBER = h.INVOICE_NUMBER
WHERE h.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND i.LAST_EXTRACTED_DAY <> h.LAST_EXTRACTED_DAY
LIMIT 100;


SELECT '§6_REQUESTED_DAY_SANITY' AS REPORT_SECTION;

SELECT
    REQUESTED_DAY,
    LAST_EXTRACTED_DAY,
    COUNT(*) AS INVOICE_COUNT
FROM SALES_DB.RAW.SALES_HEADER
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)
GROUP BY REQUESTED_DAY, LAST_EXTRACTED_DAY
ORDER BY INVOICE_COUNT DESC;


-- =============================================================================
-- §7  Invoice graph connectivity (single query view per invoice)
-- =============================================================================
SELECT '§7_INVOICE_GRAPH_SAMPLE' AS REPORT_SECTION;

WITH hdr AS (
    SELECT INVOICE_NUMBER
    FROM SALES_DB.RAW.SALES_HEADER
    WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)
    LIMIT 20
)
SELECT
    h.INVOICE_NUMBER,
    IFF(d.INVOICE_NUMBER IS NOT NULL, 1, 0) AS HAS_DELIVERY,
    IFF(cu.INVOICE_NUMBER IS NOT NULL, 1, 0) AS HAS_CUSTOMER,
    IFF(si.INVOICE_NUMBER IS NOT NULL, 1, 0) AS HAS_SOURCE_INFO,
    COALESCE(ch.CNT, 0) AS CHARGE_ROWS,
    COALESCE(pa.CNT, 0) AS PAYMENT_ROWS,
    COALESCE(it.CNT, 0) AS LINE_ROWS,
    COALESCE(io.CNT, 0) AS OPTION_ROWS
FROM hdr h
LEFT JOIN SALES_DB.RAW.SALES_DELIVERY d
    ON h.INVOICE_NUMBER = d.INVOICE_NUMBER AND d.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
LEFT JOIN SALES_DB.RAW.SALES_CUSTOMER cu
    ON h.INVOICE_NUMBER = cu.INVOICE_NUMBER AND cu.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
LEFT JOIN SALES_DB.RAW.SALES_SOURCE_INFO si
    ON h.INVOICE_NUMBER = si.INVOICE_NUMBER AND si.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
LEFT JOIN (
    SELECT INVOICE_NUMBER, COUNT(*) AS CNT
    FROM SALES_DB.RAW.SALES_CHARGES
    WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
    GROUP BY INVOICE_NUMBER
) ch ON h.INVOICE_NUMBER = ch.INVOICE_NUMBER
LEFT JOIN (
    SELECT INVOICE_NUMBER, COUNT(*) AS CNT
    FROM SALES_DB.RAW.SALES_PAYMENTS
    WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
    GROUP BY INVOICE_NUMBER
) pa ON h.INVOICE_NUMBER = pa.INVOICE_NUMBER
LEFT JOIN (
    SELECT INVOICE_NUMBER, COUNT(*) AS CNT
    FROM SALES_DB.RAW.SALES_ITEMS
    WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
    GROUP BY INVOICE_NUMBER
) it ON h.INVOICE_NUMBER = it.INVOICE_NUMBER
LEFT JOIN (
    SELECT INVOICE_NUMBER, COUNT(*) AS CNT
    FROM SALES_DB.RAW.SALES_ITEM_OPTIONS
    WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
    GROUP BY INVOICE_NUMBER
) io ON h.INVOICE_NUMBER = io.INVOICE_NUMBER
ORDER BY h.INVOICE_NUMBER;


-- =============================================================================
-- §8  SALES_INVOICE_HISTORY — merge / conflict audit
--
-- These checks PASS TRIVIALLY: the table is never written by the pipeline, so
-- both queries always return zero rows. Retained for when the per-invoice merge
-- (docs/section-05) is implemented. The same applies to the
-- HISTORY_INVALID_CONFLICT_GROUP check in the section 10 summary.
-- =============================================================================
SELECT '§8_HISTORY_CONFLICT_PAIRS' AS REPORT_SECTION;

SELECT
    CONFLICT_GROUP_ID,
    INVOICE_NUMBER,
    COUNT(*) AS ROWS_IN_GROUP,
    COUNT_IF(SNAPSHOT_ROLE = 'SUPERSEDED') AS SUPERSEDED_COUNT,
    COUNT_IF(SNAPSHOT_ROLE = 'INCOMING') AS INCOMING_COUNT,
    MIN(NET_AMOUNT) AS MIN_NET,
    MAX(NET_AMOUNT) AS MAX_NET
FROM SALES_DB.RAW.SALES_INVOICE_HISTORY
WHERE REEXTRACTION_REQUESTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
GROUP BY CONFLICT_GROUP_ID, INVOICE_NUMBER
HAVING COUNT(*) <> 2
    OR SUPERSEDED_COUNT <> 1
    OR INCOMING_COUNT <> 1
    OR MIN_NET = MAX_NET
ORDER BY INVOICE_NUMBER
LIMIT 50;


SELECT '§8_HISTORY_WITHOUT_CURRENT_HEADER' AS REPORT_SECTION;

SELECT DISTINCT hist.INVOICE_NUMBER
FROM SALES_DB.RAW.SALES_INVOICE_HISTORY hist
LEFT JOIN SALES_DB.RAW.SALES_HEADER h ON hist.INVOICE_NUMBER = h.INVOICE_NUMBER
WHERE hist.REEXTRACTION_REQUESTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND h.INVOICE_NUMBER IS NULL
LIMIT 50;


-- =============================================================================
-- §9  VARIANT columns — parsed JSON health (sample)
-- =============================================================================
SELECT '§9_VARIANT_NOT_JSON' AS REPORT_SECTION;

SELECT 'SALES_HEADER.TAGS' AS COLUMN_NAME, COUNT(*) AS BAD_ROWS
FROM SALES_DB.RAW.SALES_HEADER
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND TAGS IS NOT NULL
  AND NOT IS_ARRAY(TAGS)

UNION ALL
SELECT 'SALES_HEADER.TAXES_DETAIL', COUNT(*)
FROM SALES_DB.RAW.SALES_HEADER
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND TAXES_DETAIL IS NOT NULL
  AND NOT IS_ARRAY(TAXES_DETAIL)

UNION ALL
SELECT 'SALES_ITEMS.LINE_TAXES_DETAIL', COUNT(*)
FROM SALES_DB.RAW.SALES_ITEMS
WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
  AND LINE_TAXES_DETAIL IS NOT NULL
  AND NOT IS_ARRAY(LINE_TAXES_DETAIL);


-- =============================================================================
-- §10  PASS / FAIL summary (expect all PASS, FAIL_COUNT = 0)
-- =============================================================================
SELECT '§10_VALIDATION_SUMMARY' AS REPORT_SECTION;

WITH hdr AS (
    SELECT INVOICE_NUMBER, BRANCH_CODE
    FROM SALES_DB.RAW.SALES_HEADER
    WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND ($VALIDATION_BRANCH_CODE IS NULL OR BRANCH_CODE = $VALIDATION_BRANCH_CODE)
),
checks AS (
    SELECT
        'PK_DUPLICATE_HEADERS' AS CHECK_NAME,
        COUNT(*) AS FAIL_COUNT
    FROM (
        SELECT INVOICE_NUMBER
        FROM SALES_DB.RAW.SALES_HEADER
        WHERE LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
        GROUP BY INVOICE_NUMBER
        HAVING COUNT(*) > 1
    )

    UNION ALL
    SELECT
        'ORPHAN_SALES_ITEMS',
        COUNT(*)
    FROM SALES_DB.RAW.SALES_ITEMS c
    LEFT JOIN hdr h ON c.INVOICE_NUMBER = h.INVOICE_NUMBER
    WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND h.INVOICE_NUMBER IS NULL

    UNION ALL
    SELECT
        'ORPHAN_SALES_DELIVERY',
        COUNT(*)
    FROM SALES_DB.RAW.SALES_DELIVERY c
    LEFT JOIN hdr h ON c.INVOICE_NUMBER = h.INVOICE_NUMBER
    WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND h.INVOICE_NUMBER IS NULL

    UNION ALL
    SELECT
        'ORPHAN_SALES_PAYMENTS',
        COUNT(*)
    FROM SALES_DB.RAW.SALES_PAYMENTS c
    LEFT JOIN hdr h ON c.INVOICE_NUMBER = h.INVOICE_NUMBER
    WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND h.INVOICE_NUMBER IS NULL

    UNION ALL
    SELECT
        'ORPHAN_ITEM_OPTIONS',
        COUNT(*)
    FROM SALES_DB.RAW.SALES_ITEM_OPTIONS c
    LEFT JOIN SALES_DB.RAW.SALES_ITEMS i
        ON c.INVOICE_NUMBER = i.INVOICE_NUMBER
       AND c.ITEM_NUMBER = i.ITEM_NUMBER
       AND i.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
    WHERE c.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND i.INVOICE_NUMBER IS NULL

    UNION ALL
    SELECT
        'BRANCH_MISMATCH_ITEMS',
        COUNT(*)
    FROM SALES_DB.RAW.SALES_ITEMS i
    JOIN hdr h ON i.INVOICE_NUMBER = h.INVOICE_NUMBER
    WHERE i.LAST_EXTRACTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
      AND i.BRANCH_CODE IS NOT NULL
      AND i.BRANCH_CODE <> h.BRANCH_CODE

    UNION ALL
    SELECT
        'HISTORY_INVALID_CONFLICT_GROUP',
        COUNT(*)
    FROM (
        SELECT CONFLICT_GROUP_ID, INVOICE_NUMBER
        FROM SALES_DB.RAW.SALES_INVOICE_HISTORY
        WHERE REEXTRACTION_REQUESTED_DAY = $VALIDATION_LAST_EXTRACTED_DAY
        GROUP BY CONFLICT_GROUP_ID, INVOICE_NUMBER
        HAVING COUNT(*) <> 2
            OR COUNT_IF(SNAPSHOT_ROLE = 'SUPERSEDED') <> 1
            OR COUNT_IF(SNAPSHOT_ROLE = 'INCOMING') <> 1
    )

    UNION ALL
    SELECT
        'NO_HEADERS_LOADED',
        CASE WHEN (SELECT COUNT(*) FROM hdr) = 0 THEN 1 ELSE 0 END
)
SELECT
    CHECK_NAME,
    FAIL_COUNT,
    IFF(FAIL_COUNT = 0, 'PASS', 'FAIL') AS STATUS
FROM checks
ORDER BY STATUS DESC, CHECK_NAME;
